# Generated by Django 4.0.3 on 2022-03-07 13:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_slider_rename_about_company_about_delete_our_clients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG', unique=True, verbose_name='Номер')),
                ('choices', models.CharField(choices=[('DC', 'Диллерские центры'), ('SC', 'Cервисные центры')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
