# Generated by Django 4.0.3 on 2022-03-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_contact_description_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=255, verbose_name='Почта'),
        ),
    ]
