# Generated by Django 4.0.3 on 2022-03-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='default title', max_length=255, verbose_name='Название'),
        ),
    ]
