# Generated by Django 4.0.3 on 2022-03-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
