# Generated by Django 4.0.3 on 2022-03-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_mainpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='title',
        ),
    ]
