# Generated by Django 4.0.3 on 2022-03-11 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_mainpage_description_remove_mainpage_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='mainpage',
            old_name='titles',
            new_name='title',
        ),
    ]
