# Generated by Django 4.0.2 on 2022-03-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='descrip',
            field=models.TextField(default=False, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='album',
            name='imaged',
            field=models.ImageField(default=False, upload_to='', verbose_name='Фотка'),
        ),
        migrations.AddField(
            model_name='album',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
