# Generated by Django 4.0.2 on 2022-03-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_albumblog_photoalbum_remove_album_descrip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='title',
            field=models.CharField(default=True, max_length=255, verbose_name='Название'),
        ),
    ]
