# Generated by Django 4.0.2 on 2022-03-15 14:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_pagephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Адрес')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='KG', verbose_name='Номер')),
                ('email', models.EmailField(default='', max_length=255, verbose_name='Почта')),
                ('choices', models.CharField(choices=[('DC', 'Диллерские центры'), ('SC', 'Cервисные центры')], default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='header',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG', verbose_name='Номер'),
        ),
    ]
