# Generated by Django 4.0.2 on 2022-03-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_contactdil_remove_contact_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdil',
            name='address',
        ),
    ]
