# Generated by Django 4.0.2 on 2022-03-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_contactdil_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdil',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес'),
        ),
    ]
