# Generated by Django 4.0.2 on 2022-03-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_contactdil_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
    ]
