# Generated by Django 4.0.2 on 2022-03-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_new_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
