# Generated by Django 4.0.2 on 2022-03-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_new_options_remove_new_created_at_new_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
        ),
    ]
