# Generated by Django 4.0.2 on 2022-03-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetail',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
    ]
