# Generated by Django 4.0.2 on 2022-03-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_rename_catalog_cataloghead'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogHead',
            new_name='Catalog',
        ),
    ]
