# Generated by Django 4.0.2 on 2022-03-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_cataloghead_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('desc', models.TextField(max_length=255, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=False, verbose_name='Актуально')),
            ],
        ),
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Фото'),
        ),
    ]
