# Generated by Django 4.0.2 on 2022-03-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_category_catalog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='text',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='desc',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.AddField(
            model_name='catalog',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Названиe'),
        ),
    ]
