# Generated by Django 4.0.2 on 2022-03-28 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_rename_desc_catalog_text_rename_text_category_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='text',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='title',
        ),
    ]
