# Generated by Django 4.0.2 on 2022-03-28 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_catalog_text_remove_catalog_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
